# Generated by Django 4.0.3 on 2022-07-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0007_alter_hat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvo',
            name='section_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='locationvo',
            name='shelf_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
